aboutApp/urls.py
from django.urls import path
from . import views

app_name = 'aboutApp'

urlpatterns = [
    path('survey/', views.survey, name = 'survey'),
    path('honor/', views.honor, name = 'honor'),
]

contactApp/urls.py
from django.urls import path
from . import views

app_name = 'contactApp'

urlpatterns = [
    path('contact/', views.contact, name = 'contact'),
    path('recruit/', views.recruit, name = 'recruit'),
]

hengDaproject/urls.py
from django.contrib import admin 
from django.urls import path 
from django.conf.urls import include 
from homeApp.views import home
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', home, name = 'home'),
    path('aboutApp/', include('aboutApp.urls')),#公司简介
    path('contactApp/', include('contactApp.urls')),#人才招聘
    path('newsApp/', include('newsApp.urls')),#新闻动态
    path('productApp/', include('productApp.urls')),#产品中心
    path('scienceApp/', include('scienceApp.urls')),#科研基地
    path('serviceApp/', include('serviceApp.urls')),#服务支持
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),  # 新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    # path('search/', views.search, name='search'), 
    # path('haystack/', SearchView(), name='haystack_search'),
]

productApp/urls.py
from django.urls import path
from . import views

app_name = 'productApp'

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),
    path('productDetail/<int:id>/', views.productDetail, name='productDetail'),
]

scienceApp/urls.py
from django.urls import path
from . import views

app_name = 'scienceApp'

urlpatterns = [
    path('science/', views.science, name = 'science'),
]

homeApp/models.py
from django.db import models

# Create your models here.

homeApp/views.py
from django.shortcuts import render
from newsApp.models import MyNew
from django.db.models import Q
from productApp.models import Product
from django.views.decorators.cache import cache_page
@cache_page(60 * 15)  # 单位：秒，缓存15分钟

def home(request):
    # 新闻展报
    newList = MyNew.objects.all().filter(~Q(newType='通知公告')).order_by('-publishDate')
    postList = set()
    postNum = 0
    for s in newList:
        if s.photo:
            postList.add(s)
            postNum += 1
        if postNum == 3:  # 只截取最近的3个展报
            break
    noteList = MyNew.objects.all().filter(
            Q(newType='通知公告')).order_by('-publishDate')
    if (len(noteList) > 4):
            noteList = noteList[0:4]

    productList = Product.objects.all().order_by('-views')
    if len(productList) > 4:
        productList = productList[0:4]

    # 新闻列表
    if len(newList) > 7:
        newList = newList[0:7]
    
    # 返回结果
    return render(request, 'home.html', {
        'activmenu': 'home',
        'postList': postList,
        'newList': newList,
        'noteList': noteList,
        'productList': productList,
    })
    

homeApp/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    首页
{% endblock %}

{% block content %}
<div id="ad" class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#ad" data-slide-to="0" class="active"></li>
        <li data-target="#ad" data-slide-to="1"></li>
        <li data-target="#ad" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" style="width: 100%; height: 400px;">
        <div class="item active">
            <img src="{% static 'img/lb1.jpg' %}" alt="广告横幅 1" style="width: 100%;">
        </div>
        <div class="item">
            <img src="{% static 'img/lb2.jpg' %}" alt="广告横幅 2" style="width: 100%;">
        </div>
        <div class="item">
            <img src="{% static 'img/lb3.jpg' %}" alt="广告横幅 3" style="width: 100%;">
        </div>
    </div>
    <a class="left carousel-control" href="#ad" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#ad" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

<div class="container">
    <div class="row row-3">
        <div class="col-md-4">
            <!-- 企业概况 -->
            <span class="part1">
                <a href="{% url 'aboutApp:survey' %}">企业概况</a>
            </span>
            <span class="part1-css">
                About Us
            </span>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <div>
                <img class="img-responsive" src="{% static 'img/qy.jpg' %}">
                <p class="text1">
                    恒达科技有限公司,位于中国某高新技术产业开发区,以社会公共安全领域为主要应用方向,提供快速、准确和防伪的人脸识别产品。
                </p>
            </div>
        </div>
        <div class="col-md-8">
            <!-- 新闻动态 -->
            <span class="part1">
            <a href="#">新闻动态</a>
            </span>
            <span class="part1 en">
            /newsApp/news
            </span>
            <a class="btn btn-default btn-xs more-btn" href="{% url 'newsApp:news' 'company' %}">更多</a>
            <div class="line1">
            <div class="line2 theme"></div>
            </div>
            <div class="col-md-5">
            <div class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators nav-points">
                {% for post in postList %}
                <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}" {% if forloop.first %} class="active" {% endif %}>
                </li>
                {% endfor %}
                </ol>
                <!-- 轮播(Carousel)项目 -->
                <div class="carousel-inner">
                {% for post in postList %}
                <div {% if forloop.first %} class="item active" {% else %} class="item" {% endif %} style="background-size:cover;">
                    <a href="{% url 'newsApp:newDetail' post.id %}">
                    <img src="{{post.photo.url}}" class="img-responsive" onload="DrawImage(this)">
                    <div class="carousel-caption nav-title">{{post.title}}</div>
                    </a>
                </div>
                {% endfor %}
                </div>
            </div>
            </div>
            <div class="col-md-7">
            <ul class="list-unstyled list-new">
                {% for new in newList %}
                <li>
                <a href="{% url 'newsApp:newDetail' new.id %}">
                    {{new.title|truncatechars:"25"}}
                </a>
                <span>{{new.publishDate|date:"Y-m-d"}}</span>
                </li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
    <div class="row row">
        <div class="col-md-4">
            <!-- 通知公告 -->
            <span class="part1">
            <a href="#">通知公告</a>
            </span>
            <span class="part1 en">
            &nbsp;&nbsp;/ Public Release
            </span>
            <a class="btn btn-default btn-xs more-btn" 
            href="{% url 'newsApp:news' 'notice' %}">+&nbsp;&nbsp;更多
            </a>
            <div class="line1">
            <div class="line2 theme"></div>
            </div>
            <div>
            <img class="img-responsive" src="{% static 'img/note.jpg' %}" style="height: 140px; width: 100%;">
            <ul class="list-unstyled list-new">
                {% for note in noteList %}
                <li>
                <a href="{% url 'newsApp:newDetail' note.id %}">
                    {{note.title|truncatechars:"25"}}
                </a>
                <a href="{% url 'newsApp:newDetail' note.id %}" class="public-detail">
                    查看详情>
                </a>
                </li>
                {% endfor %}
            </ul>
            </div>
        </div>
        <div class="col-md-4">
            <!-- 科研基地 -->
            <span class="part1">
                <a href="{% url 'scienceApp:science' %}">科研基地</a>
            </span>
            <span class="part1 en">
                &nbsp;&nbsp;/ Technology Center
            </span>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <a href="{% url 'scienceApp:science' %}">
                <img class="img-responsive" src="{% static 'img/ky.jpg' %}" style="width: 100%; height: 140px;">
            </a>
            <p class="text1">
                <font color="#d30a1c">恒达科技科研基地</font><br>
                恒达科研基地分为计算机视觉、机器人和视觉深度学习三个事业部,共拥有恒达科研基地分为计算机视觉、机器人和视觉深度学习三个事业部,共拥有
                恒达科研基地分为计算机视觉、机器人和视觉深度学习三个事业部,共拥有恒达科研基地分为计算机视觉、机器人和视觉深度学习三个事业部,共拥有
            </p>
        </div>
        <div class="col-md-4">
            <!-- 联系我们 -->
            <span class="part1">
            <a href="{% url 'contactApp:contact' %}">联系我们</a>
            </span>
            <span class="part1 en">
            &nbsp;&nbsp;/ Contact us
            </span>
            <div class="line1">
            <div class="line2 theme"></div>
            </div>
            <div>
            <ul class="list-unstyled procurement-li">
                <li>业务质询一: 111-XXXXXX</li>
                <li>业务质询二: 222-XXXXXX</li>
                <li>业务电话: 0111-XXXXXX</li>
                <li>咨询电话: 0222-XXXXXX</li>
                <li>企业传真: 0222-XXXXXX</li>
                <li>地址: 某某某新区某某大道1号</li>
                <li>邮编: XXXXXXX</li>
                <li>网址: <a href="http://python3web.com">http://python3web.com</a></li>
            </ul>
            <div class="platform"><a href="{% url 'contactApp:contact' %}">详情</a></div>
            </div>
        </div>
    </div>
    <div class="row">
    <!-- 产品中心 -->
    <div class="col-md-12">
        <span class="part1">
        <a href="{% url 'productApp:products' 'robot' %}">产品中心</a>
        </span>
        <span class="part1 en">
        &nbsp;&nbsp;/ Products
        </span>
        <a class="btn btn-default btn-xs more-btn" href="{% url 'productApp:products' 'robot' %}">
        +&nbsp;&nbsp;更多
        </a>
        <div class="line1" style="margin-bottom:5px;"></div>
        <div class="line2 theme"></div>
    </div>
    </div>
    <div class="col-md-12 col-pro">
    <div id="Carousel" class="carousel slide" style="margin-bottom:30px">
        <ol class="carousel-indicators" style="display:none">
        <li data-target="#Carousel" data-slide-to="0" class="active"></li>
        </ol>
        <div class="carousel-inner">
        <div class="item active">
            <div class="row">
            {% for product in productList %}
            <div class="col-md-3 pro-images">
                <a href="{% url 'productApp:productDetail' product.id %}" class="thumbnail">
                {% for img in product.productImgs.all %}
                    {% if forloop.first %}
                    <img src="{{img.photo.url}}" alt="产品图片" class="img-responsive" onload="DrawImage(this)">
                    {% endif %}
                {% endfor %}
                </a>
                <div class="carousel-caption nav-title">{{product.title}}</div>
            </div>
            {% endfor %}
            </div>
        </div>
        </div>
    </div>
    </div>
    <div class="row row">
        <!-- 友情链接 -->
        <div class="col-md-12">
        </div>
    </div>
</div>

<!-- CSS文件导入 -->
<link href="{% static 'css/home.css' %}" rel="stylesheet">

<!-- 图像裁剪脚本 -->
<script src="{% static 'js/jqthumb.min.js' %}"></script>
<script>
    // 处理缩略图
    function DrawImage(hotimg) {
        $(hotimg).jqthumb({
        width: "100%", // 宽度
        height: "280px", // 高度
        method: "auto", // 缩放方式
        });
  }
</script>
{% endblock %}