aboutApp/urls.py
from django.urls import path
from . import views

app_name = 'aboutApp'

urlpatterns = [
    path('survey/', views.survey, name = 'survey'),
    path('honor/', views.honor, name = 'honor'),
]

contactApp/urls.py
from django.urls import path
from . import views

app_name = 'contactApp'

urlpatterns = [
    path('contact/', views.contact, name = 'contact'),
    path('recruit/', views.recruit, name = 'recruit'),
]

hengDaproject/urls.py
from django.contrib import admin 
from django.urls import path 
from django.conf.urls import include 
from homeApp.views import home
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', home, name = 'home'),
    path('aboutApp/', include('aboutApp.urls')),#公司简介
    path('contactApp/', include('contactApp.urls')),#人才招聘
    path('newsApp/', include('newsApp.urls')),#新闻动态
    path('productApp/', include('productApp.urls')),#产品中心
    path('scienceApp/', include('scienceApp.urls')),#科研基地
    path('serviceApp/', include('serviceApp.urls')),#服务支持
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from . import views

app_name = 'newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),  # 新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    # path('search/', views.search, name='search'), 
    # path('haystack/', SearchView(), name='haystack_search'),
]

productApp/urls.py
from django.urls import path
from . import views

app_name = 'productApp'

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),
    path('productDetail/<int:id>/', views.productDetail, name='productDetail'),
]

scienceApp/urls.py
from django.urls import path
from . import views

app_name = 'scienceApp'

urlpatterns = [
    path('science/', views.science, name = 'science'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">  <!-- 修正语言代码为 zh-CN -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>恒达科技|{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="container top"> 
        <div class="row">
            <div class="col-md-6">
                <a>
                    <img class="img-responsive" src="{% static 'img/logo.svg' %}">
                </a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="phone ant">
                    <span class="glyphicon glyphicon-phone"></span> 电话: 400 1111 0000 &nbsp; &nbsp;
                </a>
            </div>
            <div class="col-md-3 hidden-xs">
                <a class="mail ant">
                    <span class="glyphicon glyphicon-envelope"></span> 邮箱: hengda@16.com
                </a>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container">  
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example" aria-expanded="false">
                    <span>导航栏</span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example">
                <ul class="nav navbar-nav" style="width: 100%;">
                    <li class="nav-top" id="home"><a href="{% url 'home'%}">首页</a></li>
                    <li class="dropdown nav-top" id="about">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">公司简介</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'aboutApp:survey' %}">企业概况</a></li>
                            <li><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top" id="news">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">新闻动态</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'newsApp:news' 'company' %}">企业要闻</a></li>
                            <li><a href="{% url 'newsApp:news' 'industry' %}">行业新闻</a></li>
                            <li><a href="{% url 'newsApp:news' 'notice' %}">通知公告</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top" id="products">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">产品中心</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'productApp:products' 'robot' %}">家用机器人</a></li>
                            <li><a href="{% url 'productApp:products' 'monitor' %}">智能监控</a></li>
                            <li><a href="{% url 'productApp:products' 'face' %}">人脸识别解决方案</a></li>
                        </ul>
                    </li>
                    <li class="dropdown nav-top" id="service">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">服务支持</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'serviceApp:download' %}">资料下载</a></li>
                            <li><a href="{% url 'serviceApp:platform' %}">人脸识别开放平台</a></li>
                        </ul>
                    </li>
                    <li class="nav-top" id="science"><a href="{% url 'scienceApp:science' %}">科研基地</a></li>
                    <li class="dropdown nav-top" id="contactapp">
                        <a href="#" class="dropdown-toggle on" data-toggle="dropdown">人才招聘</a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></li>
                            <li><a href="{% url 'contactApp:recruit' %}">加入恒达</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="line"></div>

    {% block content %}
    {% endblock %}

    <!-- 页脚部分 -->
    <div class="container web-footer">  <!-- 页脚容器 -->
        <div class="row" id="map-footer">
            <div class="col-md-2">
                <dl>
                    <dt>公司简介</dt>
                    <dd><a href="{% url 'aboutApp:survey' %}">企业概况</a></dd>
                    <dd><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></dd>
                </dl>
            </div>
            <div class="col-md-2">
                <dl>
                    <dt>产品中心</dt>
                    <dd><a href="{% url 'productApp:products' 'robot' %}">家用机器人</a></dd>
                    <dd><a href="{% url 'productApp:products' 'monitoring' %}">智能监控</a></dd>
                    <dd><a href="{% url 'productApp:products' 'face' %}">人脸识别解决方案</a></dd>
                </dl>
            </div>
            <div class="col-md-2">
                <dl>
                    <dt>服务支持</dt>
                    <dd><a href="{% url 'serviceApp:download' %}">资料下载</a></dd>
                    <dd><a href="{% url 'serviceApp:platform' %}">人脸识别开放平台</a></dd>
                </dl>
            </div>
            <div class="col-md-2">
                <dl>
                    <dt>人才招聘</dt>
                    <dd><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></dd>
                    <dd><a href="{% url 'contactApp:recruit' %}">加入恒达</a></dd>
                </dl>
            </div>
            <div class="col-md-4" id="wx">
                <p>扫描二维码,关注我们</p>
                <img class="qrimg" src="{% static 'img/qr.png' %}" alt="wx">
                <p>客服热线：<b style="font-size:20px">400 111 2222</b></p>
            </div>
        </div>
        <!-- 版权 -->
        <div class="row" id="patent-footer">
            <p>© 2019 Python Web 企业门户 版权所有 | 苏 ICP 备 19006378 号</p>
        </div>
    </div>

</body>
<script>
    $(function(){
        $(".dropdown").mouseover(function () {
            $(this).addClass("open");
        }).mouseleave(function () {
            $(this).removeClass("open");
        });
    });
</script>
<script type="text/JavaScript">
    $('#{{activmenu}}').addClass("active");
    $('#{{smenu}}').addClass("active");
</script>
</html>